#
## sam_2018_cpt_rad library module
## Description: Contains dictionaries of 2018 CPT codes and descriptions for radiology modalities and search functions.
##              These codes were taken from "http://www.mainstreetradiology.com/common/pages/UserFile.aspx%3FfileId%3D895629"
##              The CPT codes are for the following modalities; CT, FLUORO, MAMMO, MRI,  NUCLEAR, PET, US, XRAY   
## Disclaimer: I noticed typos in some of the definitions for s few of the CPT codes but intentionally did not correct them
##
## v1.0 sdomingo 2019 .Inital version
#
## Dictionary names are; RAD_CPT_CT_dict, RAD_CPT_FLUORO_dict, RAD_CPT_MAMO_dict, RAD_CPT_MRI_dict,     
##                       RAD_CPT_NUCLEAR_dict,  RAD_CPT_PET_dict,  RAD_CPT_US_dict,  RAD_CPT_XRAY_dict, 
## CT Dictionary
RAD_CPT_CT_dict = { '70450': 'CT BRAIN without contrast', 
                    '70460': 'CT BRAIN with contrast', 
                    '70470': 'CT BRAIN w/o & with contrast',
                    '70480': 'CT ORBIT/SKULL without contrast',
                    '70481': 'CT ORBITS/SKULL with contrast',
                    '70482': 'CT ORBIT/SKULL w/o & with contrast',
                    '70486': 'CT MAXILLOFACIAL without contrast',
                    '70488': 'CT FACE w/o & with contrast',
                    '70490': 'CT NECK SOFT TISSUE without contrast',
                    '70491': 'CT NECT SOFT TISSUE with contrast',
                    '70492': 'CT NECK SOFT TISSUE w/o & with contrast',
                    '70496': 'CT ANGIO HEAD with and/or w/o contrast',
                    '70498': 'CT ANGIO/NECK with and/or w/o contrast',
                    '71250': 'CT CHEST without contrast',
                    '71260': 'CT CHEST with contrast',
                    '71270': 'CT CHEST w/o & with contrast',
                    '71275': 'CT ANGIOGRAPHY/CHEST with and/or w/o contrast',
                    '72125': 'CT CERVICAL SPINE without contrast',
                    '72126': 'CT CERVICAL SPINE with contrast',
                    '72127': 'CT CERVICAL SPINE w/o & with contrast',
                    '72128': 'CT THORACIC SPINE without contrast',
                    '72129': 'CT THORACIC SPINE with contrast',
                    '72130': 'CT THORACIC SPINE w/o & with contrast',
                    '72131': 'CT LUMBAR SPINE without contrast',
                    '72132': 'CT LUMBAR SPINE with contrast',
                    '72133': 'CT LUMBAR SPINE w/o & with contrast',
                    '72191': 'CT ANGIO PELVIS with and/or w/o contrast',
                    '72192': 'CT PELVIS without contrast',
                    '72193': 'CT PELVIS with contrast',
                    '72194': 'CT PELVIS w/o & with contrast',
                    '73200': 'CT UPPER EXTREMITY without contrast',
                    '73201': 'CT UPPER EXTREMITY with contrast',
                    '73202': 'CT UPPER EXTREMITY w/o & with contrast',
                    '73206': 'CT ANGIO UPPER EXTREM with and/or w/o contrast',
                    '73700': 'CT LOWER EXTREMITY without contrast',
                    '73701': 'CT LOWER EXTREMITY with contrast',
                    '73702': 'CT LOWER EXTREMITY w/o & with contrast',
                    '73706': 'CT ANGIO LOWER EXT with and/or w/o contrast',
                    '74150': 'CT ABDOMEN w/o contrast',
                    '74160': 'CT ABDOMEN with contrast',
                    '74170': 'CT ABDOMEN w/o & with contrast',
                    '74174': 'CT ANGIO ABD & PELVIS contrast with & w/o contrast',
                    '74175': 'CT ANGIO ABD with contrast/noncontrast',
                    '74176': 'CT ABDOMEN & PELVIS w/o contrast',
                    '74177': 'CT ABDOMEN & PELVIS with contrast',
                    '74178': 'CT ABDOMEN & PELVIS w/o contrast 1/>body re',
                    '74261': 'CT ABDOMEN w/o contrast',
                    '74262': 'CT ABDOMEN w/o contrast',
                    '74263': 'CT ABDOMEN w/o contrast',
                    '73636': 'CT BRAIN w/o contrast',
                    '73731': 'CT BRAIN with contrast',
                    '73827': 'CT BRAIN w/o & with contrast',
                    '73922': 'CT ORBIT/SKULL without contrast',
                    '74018': 'CT ORBITS/SKULL with contrast',
                    '74113': 'CT ORBIT/SKULL w/o & with contrast',
                    '74209': 'CT MAXILLOFACIAL without contrast',
                    '74304': 'CT FACE with contrast',
                    '74400': 'CT FACE w/o & with contrast',
                    '74495': 'CT NECK SOFT TISSUE without contrast',
                    '74591': 'CT NECT SOFT TISSUE with contrast'}
## FLUORO Dictionary
RAD_CPT_FLUORO_dict =  { '74210': 'FLUORO Upper Esophagram',
                        '74220': 'FLUORO ESOPHAGUS EXAM',
                        '74241': 'FLUORO UPPER GI SERIES',
                        '74247': 'FLUORO UPPER GI TRACT WITH AIR',
                        '74249': 'FLUORO UGI & SB WITH AIR',
                        '74250': 'FLUORO SMALL BOWEL SERIES',
                        '74270': 'FLUORO BARIUM ENEMA',
                        '74280': 'FLUORO BARIUM ENEMA W/AIR CONT',
                        '74400': 'FLUORO IVP'}
## MAMMO  Dictionary
RAD_CPT_MAMO_dict = {'77063': 'MAMMOGRAPHY 3D DIGITAL SCREENING', 
                     '77065': 'MAMMOGRAPHY-Diagnostic UNILATERAL',
                     '77066': 'MAMMOGRAPHY-Diagnostic- BILATERAL',
                     '77067': 'MAMMOGRAPHY SCREENING'}
## MRI  Dictionary
RAD_CPT_MRI_dict = {'70336': 'MRI TEMPOROMANDIBULAR JOI', 
                    '70540': 'MRI SOFT TISSUE NECK,ORBIT without contrast',
                    '70542': 'MRI SOFT TISSUE NECK,ORBIT with contrast',
                    '70543': 'MRI NECK,ORBIT w/o & with contrast',
                    '70544': 'MRA HEAD without contrast',
                    '70545': 'MRA HEAD with contrast',
                    '70546': 'MRA HEAD w/o & with contrast',
                    '70547': 'MRA NECK without contrast',
                    '70548': 'MRA NECK/CAROTID with contrast',
                    '70549': 'MRA/NECK w/o & with contrast',
                    '70551': 'MRI BRAIN without contrast',
                    '70552': 'MRI BRAIN with contrast',
                    '70553': 'MRI BRAIN w/o & with contrast',
                    '71550': 'MRI CHEST without contrast',
                    '71551': 'MRI CHEST with contrast',
                    '71552': 'MRI CHEST w/o & with contrast',
                    '71555': 'MRA CHEST',
                    '72141': 'MRI CERV.SPINE without contrast',
                    '72142': 'MRI CERV SPINE with contrast',
                    '72146': 'MRI THORACIC without contrast',
                    '72147': 'MRI THORACIC with contrast',
                    '72148': 'MRI LUMBAR SPINE without contrast / MRI LUMBAR PLEXUS',
                    '72149': 'MRI LUMBAR SPINE with contrast',
                    '72156': 'MRI/CERV SPINE w/o & with contrast',
                    '72157': 'MRI THORACIC w/o & with contrast',
                    '72158': 'MRI LUMBAR SPINE w/o & with contrast',
                    '72159': 'MRI SPINE Angiography',
                    '72195': 'MRI PELVIS without contrast',
                    '72196': 'MRI PELVIS with contrast',
                    '72197': 'MRI PELVIS w/o & with contrast',
                    '72198': 'MRA PELVIS',
                    '73218': 'MRI UPPER EXT. NON JOINT without contrast',
                    '72197': 'MRI PELVIS w/o & with contrast',
                    '72198': 'MRA PELVIS',
                    '73218': 'MRI UPPER EXT. NON JOINT without contrast',
                    '73219': 'MRI UPPER EXT. NON JOINT with contrast',
                    '73220': 'MRI UPPER EXT NON JOINT w/o & with contrast',
                    '73221': 'MRI UPPER EXT. JOINT without contrast',
                    '73222': 'MRI UPPER EXT JOINT with contrast',
                    '73223': 'MRI UPPER JOINT w/o & with contrast',
                    '73225': 'MRA UPPER EXTREMITY',
                    '73718': 'MRI LOWER EXT without contrast',
                    '73719': 'MRI LOWER EXT with contrast',
                    '73720': 'MRI LOWER EX. w/o & with contrast',
                    '73721': 'MRI LOWER EXT JOINT without contrast',
                    '73722': 'MRI LOWER EXT JOINT with contrast',
                    '73723': 'MRI/JOINT LOW EXTREMITY w/o & with contrast',
                    '73725': 'MRA.ANGIO,LOWER EXTREMITY',
                    '74181': 'MRI ABDOMEN without contrast',
                    '74182': 'MRI/ABDOMEN with contrast',
                    '74183': 'MRI ABD. w/o & with contr',
                    '74185': 'MRA ABDOMEN',
                    '77058': 'MRI BREAST UNILATERAL',
                    '77059': 'MRI BREAST BILATERAL'}
## NUCLEAR Dictionary
RAD_CPT_NUCLEAR_dict = {'78012':'NUCLEAR EXAM THYROID (UPTAKE only)', 
                        '78012':'NUCLEAR EXAM THYROID (UPTAKE only)',
                        '78014':'NUCLEAR EXAM THYROID (WITH UPTAKE)',
                        '78013':'NUCLEAR EXAM THYROID (WITH IMAGING ONLY)',
                        '78070':'NUCLEAR EXAM PARATHYROID SCAN',
                        '78071':'NUCLEAR EXAM PARATHYROID SCAN with SPECT',
                        '78206':'NUCLEAR LIVER SCAN SPECT(HEMANGIOMA)',
                        '78215':'NUCLEAR LIVER/SPLEEN SCAN static',
                        '78226':'NUCLEAR HEPATOBILIARY SCAN',
                        '78227':'NUCLEAR HEPATOBILIARY SCAN WITH PHARM',
                        '78290':'NUCLEAR MECKELS SCAN',
                        '78306':'NUCLEAR BONE SCAN WHOLE BODY',
                        '78315':'NUCLEAR BONE SCAN 3 PHASE',
                        '78320':'NUCLEAR BONE SCAN SPECT',
                        '78452':'MyoCardial Perfusion Imaging/Exercise with 93015',
                        '78452':'MyoCardial Perfusion Imaging/Pharmacologic with 93015',
                        '78472':'NUCLEAR MUGA SCAN CARDIA IMAGING',
                        '78607':'NUCLEAR Brain Spect (DaTscan)',
                        '78707':'NUCLEAR RENAL SCAN WITH MAG 3',
                        '78708':'NUCLEAR RENAL SCAN WITH LASIX OR CAPTOPRIL',
                        '78800':'NUCLEAR GALLIUM SCAN with 78803',
                        '78804':'NUCLEAR OCTREO SCAN with 78803',
                        '78807':'NUCLEAR SCAN FOR INFLAMATION with spect'}
## PET Dictionary
RAD_CPT_PET_dict = {'78608': 'PET BRAIN IMAG', 
                    '78814': 'PET SCAN WITH CT Limited',
                    '78815': 'PET SCANN with CT Skull to mid thigh',
                    '78816': 'PET SCAN with CT full body'}
## US Dictionary
RAD_CPT_US_dict = { '76506': 'U/S EXAM OF HEAD', 
                    '76536': 'U/S Soft Tissue Neck(thyroid,parathyroid,etc.)',
                    '76604': 'U/S CHEST',
                    '76641': 'U/S BREAST(uni or bi)',
                    '76700': 'U/S ABDOMEN COMPLETE',
                    '76705': 'U/S ABDOMEN(limited)',
                    '76770': 'U/S RETRO(renal,aorta,nodes)',
                    '76775': 'U/S RETRO-limited',
                    '76776': 'U/S TRANSPLANTED KIDNEY',
                    '76800': 'U/S ECHO EXAM SPINAL CANAL',
                    '76801': 'U/S OB FIRST TRIMESTER',
                    '76802': 'U/S OB/FIRST TRI/EACH ADD',
                    '76805': 'U/S OB-GYN > 14 WEEKS',
                    '76810': 'U/S OB > 14 WEEKS/EACH ADD',
                    '76811': 'U/S OB MATERN/EVAL&DET EX',
                    '76812': 'U/S OB MATERN/EVAL&DET EX/EACH ADD',
                    '76813': 'U/S NUCHAL TRANSLUCENCY',
                    '76814': 'U/S Nuchal Translucency/EACH ADD',
                    '76815': 'U/S OB LIMITED',
                    '76816': 'U/S OB LIMITED FOLLOW UP',
                    '76817': 'U/S OB TRANSVAG',
                    '76830': 'U/S TRANSVAGINAL',
                    '76831': 'U/S HYSTEROGRAM WITH DOPPLER',
                    '76856': 'U/S PELVIS-NON OB',
                    '76857': 'U/S PELVIS-NON OB LIMITED',
                    '76870': 'U/S SCROTUM',
                    '76870': 'U/S SCROTUM with Doppler 93975',
                    '76881': 'U/S EXTREMITY NON VASCULAR',
                    '76882': 'U/S EXTREMITY NON VASCULAR LIMITED',
                    '93880': 'U/S CAROTID DOPPLER/DUPLEX',
                    '93926': 'U/S DUPLEX SCAN LOW EXT ARTERY r/o pseudo',
                    '93970': 'U/S VENOUS DUPLEX/EXTREMITY',
                    '93971': 'U/S VENOUS DUPLEX/EXTRM/UNILA',
                    '93975': 'U/S DOPPLER,ABDOMINAL/PELVIC',
                    '93976': 'U/S LIMITED STUDY DUPLEX SCAN',
                    '93990': 'U/S DUPLEX SCAN OF HEMODIALYS'}
## XRAY Dictionary
RAD_CPT_XRAY_dict = {'70030': 'X-RAY EYE FOR FOREIGN BOD',
                    '70100': 'XRAY MANDIBLE < 4 VIEWS',
                    '70110': 'X-RAY EXAM OF MANDIBLE 4 VIEWS',
                    '70140': 'XRAY FACIAL BONES < 3VIEWS',
                    '70150': 'X-RAY FACIAL BONES 3VIEWS',
                    '70160': 'XRAY NASAL BONES 3 VIEWS+',
                    '70210': 'XRAY SINUSES < 3 VIEWS',
                    '70220': 'XRAY SINUSES 3 OR MORE VIEWS',
                    '70250': 'XRAY SKULL < 4 VIEWS',
                    '70260': 'XRAY SKULL 4VIEWS',
                    '70360': 'XRAY NECK SOFT TISSUE',
                    '71010': 'XRAY CHEST, ONE VIEW',
                    '71020': 'XRAY CHEST, TWO VIEWS',
                    '71021': 'XRAY CHEST W/APICAL LORDO',
                    '71022': 'XRAY CHEST W/OBLIQUE PROJEC',
                    '71023': 'XRAY CHEST W/FLUORO',
                    '71030': 'XRAY CHEST 4 VIEWS',
                    '71034': 'XRAY CHEST 4 VIEWS W/FLUOROS.',
                    '71035': 'XRAY CHEST LATERAL DECUBITUS',
                    '71100': 'XRAY RIBS,UNILAT.,TWO VIEWS',
                    '71101': 'XRAY RIBS INCL CHEST 3 VI',
                    '71110': 'XRAY RIB BILAT 3 VIEWS',
                    '71111': 'XRAY RIBS BILATERAL INCL CHEST 4 VI',
                    '71120': 'XRAY STERNUM 2 VIEWS',
                    '71130': 'XRAY STERNO CLAVI JOINT 3 VIEWS',
                    '72010': 'XRAY SPINE, ENTIRE AP & LAT',
                    '72020': 'XRAY SPINE ONE VIEW',
                    '72040': 'XRAY CERVICAL SPINE < 4 VIEWS',
                    '72050': 'XRAY CERVICAL SPINE 4 or 5 VIEWS',
                    '72052': 'XRAY SPINE CERV INCL OBLI 6VIEWS',
                    '72069': 'XRAY SPINE THORACOLUMBAR SCOLIOSIS',
                    '72070': 'XRAY THORACIC SPINE 2 VIEWS',
                    '72072': 'XRAY SPINE THORACIC 3 VIE',
                    '72074': 'XRAY SPINE THORACIC 4 VIE',
                    '72080': 'XRAY SPINE THORACOLUMBAR',
                    '72090': 'XRAY SCOLIOSIS STUDY ERECT & SUPINE',
                    '72100': 'XRAY LUMBAR SPINE < 4 VIEWS',
                    '72110': 'XRAY LUMBAR SPINE 4 VIEWS',
                    '72114': 'X-RAY LUMBAR SPINE 6 VIEWS',
                    '72120': 'X-RAY LUMBAR SPINE <4 VIEW',
                    '72170': 'XRAY PELVIS 1 OR 2 VIEWS',
                    '72190': 'XRAY PELVIS 3 VIEWS',
                    '72200': 'XRAY SACROILIAC JOINTS < 3 VIEWS',
                    '72202': 'XRAY SACROILIAC JOINTS 3VIEW',
                    '72220': 'XRAY COCCYX/SACRUM 2VIEWS',
                    '73000': 'XRAY CLAVICLE',
                    '73010': 'XRAY SCAPULA, COMPLETE',
                    '73020': 'XRAY SHOULDER MIN 1 VIEWS',
                    '73030': 'XRAY SHOULDER 2 VIEWS',
                    '73040': 'XRAY SHOULDER ARTHROGRAPHY',
                    '73050': 'X-RAY ACOMIOCLAVICULAR JOINTS',
                    '73060': 'XRAY HUMERUS 2 VIEWS',
                    '73070': 'XRAY ELBOW TWO VIEWS',
                    '73080': 'XRAY ELBOW THREE VIEWS',
                    '73085': 'XRAY ELBOW ARTHROGRAPHY',
                    '73090': 'XRAY FOREARM TWO VIEWS',
                    '73092': 'X-RAY EXAM OF ARM, INFANT',
                    '73100': 'XRAY WRIST 2 VIEWS',
                    '73110': 'XRAY WRIST MIN 3 VIEWS',
                    '73115': 'XRAY WRIST ARTHROGRAPHY',
                    '73120': 'XRAY HAND 2 VIEWS',
                    '73130': 'XRAY HAND MIN 3 VIEWS',
                    '73140': 'XRAY FINGER 2 VIEWS',
                    '73500': 'XRAY XRAY HIP 1 VIEW',
                    '73510': 'XRAY HIP MIN TWO VIEWS',
                    '73520': 'XRAY HIP BILAT TWO VIEWS',
                    '73525': 'XRAY HIP ARTHROGRAPHY',
                    '73540': 'X-RAY EXAM OF PELVIS INFANT OR CHILD',
                    '73550': 'X-RAY FEMUR TWO VIEWS',
                    '73560': 'X-RAY KNEE 1 OR 2 VIEWS',
                    '73562': 'X-RAY KNEE-3 VIEWS',
                    '73564': 'X-RAY EXAM OF KNEE 4 VIEWS',
                    '73565': 'X-RAY KNEE,BILATERAL STANDING',
                    '73580': 'X-RAY KNEE ARTHROGRAPHY',
                    '73590': 'X-RAY TIBIA/FIBULA',
                    '73592': 'X-RAY EXAM OF LEG, INFANT',
                    '73600': 'X-RAY ANKLE',
                    '73610': 'X-RAY ANKLE BILATERAL',
                    '73615': 'X-RAY ANKLE ARTHROGRAPHY',
                    '73620': 'X-RAY FOOT 2 VIEWS',
                    '73630': 'X-RAY FOOT,COMPLETE',
                    '73650': 'X-RAY HEEL,TWO VIEWS',
                    '73660': 'X-RAY TOE(S)',
                    '74000': 'X-RAY ABDOMEN AP VIEW',
                    '74010': 'X-RAY EXAM OF ABDOMEN WITH OBLIQUE',
                    '74020': 'X-RAY EXAM OF ABDOMEN SUPINE & ERECT',
                    '74022': 'X-RAY ABDOMEN COMPLETE WITH AP CHEST',
                    '76010': 'X-RAY, NOSE TO RECTUM CHILD',
                    '77072': 'X-RAY BONE AGE STUDIES',
                    '77073': 'X-RAY BONE LENGTH EVALUATION SCANOGRAM',
                    '77074': 'X-RAY BONE SURVEY limited',
                    '77075': 'X-RAY BONE SURVEY COMPLETE',
                    '77076': 'X-RAY BONE EVALUATION infant',
                    '77080': 'X-RAY DEXA/BONE DENSITY STUDY'}

#
## Useful functions to search 2018 RAD CPT dictionary
#
############################################################################
# Find exact match of a value in a dictionary and return key
#
def find_first_key_exact(input_dict, value):
    return next((k for k, v in input_dict.items() if v== value), None)
############################################################################
# Convert a dictionary (keys & value strings) to all lower case characters
#
def lower_dict(d):
   new_dict = dict((k.lower(), v.lower()) for k, v in d.items())
   return new_dict
############################################################################
# Convert a dictionary (keys & value strings) to all lower case characters
#
def upper_dict(d):
   new_dict = dict((k.upper(), v.upper()) for k, v in d.items())
   return new_dict
############################################################################
# Find value string that contains value and return all possible keys
# This normalizes the dictionary and value to upper case characters
def find_all_keys_containing(input_dict, value):
    upper_case_dict = upper_dict(input_dict)
    return {k for k, v in upper_case_dict.items() if v.find(value.lower()) != -1}
